'this is the class for the debugger object
'comments before the methods are the class description!
property get/let remoteIP()
property let/get remotePort()
property get success()
Function connect([ip], [port])
Sub disconnect()
Function readMem(addr, size)
Function readString(addr, unicode) 'methods can have their own inline comment help strings for objbrowser
Function writeMem(addr, hexData)
Function setBp(addr)
Function delBp(addr)
Function setCmt(addr, comment)
Function getCmt(addr)
Function setLabel(addr, labelName)
Function getRegisters()
Function setReg(regName, value)
Function stepInto()
Function run()
Function pause()
Function getModules()
Function getMod(addr)
Function notify(pattern)
Function notifyRange(startAddr, endAddr)
Function unnotify(pattern)
Function unnotifyRange(startAddr, endAddr)
Function optRva(enable)
Function status()
Function disasm(addr, count)
Function eval(expr)
Function getReg(regName)
